inherit_from: .rubocop_todo.yml
#require: rubocop-rspec

AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - Gemfile
    - Rakefile
    - '*.gemspec'
    - 'tmp/**'
    - 'lib/saharspec/matchers/request_webmock.rb'
  DisplayCopNames: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Naming/PredicateName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '{}'

Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/FormatStringToken:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false